### ISSUE TITLE
What does “Outliner focused” mean?

### ISSUE THREAD

**Issue by DutchPete** [efemkay/obsidian-listive-theme#5]
What does this mean in practical terms?

A new paragraph does not start as a bulleted list, and a tab does not produce a bullet, you have to add `-`

So, how is this different from the default theme?

This is not a criticism, I think the theme is very attractive.

**Comment by efemkay** [comment]
Hey @DutchPete,

That's fair question. I guess it would be useful for me to clarify that in the readme.

Anyway, themes cannot do certain functionality like auto bullet. That's for Outliner plugin (which i use personally use heavily and support financially). What the theme offer is customisation that focused on bullets / lists to complement that plugin (not to replace)

Technically other themes can do that no doubt (which I think u can observe most themes just change colour scheme and font type).

The outliner focused customisation this theme offer are (not exhaustive)
1. Header customisation with bullet list in mind (like under for header for list header, most theme doesn't consider this)
2. Spacing between list item that's user customisable
3. List indent customisation
4. Indentation guide for reading view separate from editing view because Outliner plugin doesn't support reading view
5. List embed, where u can embed list block seamlessly

These are the things I use personally and I'm creating theme for those who might find it useful. I come from logseq before this

![Screenshot_20230708_121602_Obsidian](https://github.com/efemkay/obsidian-listive-theme/assets/42369515/d609abc4-4961-4e1e-b8c1-72cd9afe5031)

**Comment by DutchPete** [comment]
Hi there @efemkay

Thanks for your detailed reply, it is clear.
You say you were using Logseq before, I have recently also started using Logseq hence my question.

Are you creating a Logseq style theme?

**Comment by efemkay** [comment]
Well, not really. But greatly influenced by it. I really wanted to create the bullet threading feature from logseq, but that requires a plugin to help me out. I never done js plugin so I don't think it will be anytime soon as front end dev isn't what I do. I'm an engineer.

**Comment by DutchPete** [comment]
Yes, that bullet threading feature is very useful, I use it.
Anyway, thanks for your explanation, and congrats with Listive, very nice!
